export const STORE_REQUEST = "STORE_REQUEST";
export const STORE_RECEIVE = "STORE_RECEIVE";
export const STORE_RECEIVE_ERROR = "STORE_RECEIVE_ERROR";

export const STORE_DETAILS_REQUEST = "STORE_DETAILS_REQUEST";
export const STORE_DETAILS_RECEIVE = "STORE_DETAILS_RECEIVE";
export const STORE_DETAILS_RECEIVE_ERROR = "STORE_DETAILS_RECEIVE_ERROR";